### ISSUE TITLE
Virtual environment already activated

### ISSUE THREAD

**Issue by shiwenqin** [JeanKaddour/NoTrainNoGain#2]
Hi, Thanks for the amazing repository.
I'm trying to setup the bert environment as per instruction, but the following error raises when I run `poetry shell`
'''
Virtual environment already activated: /localdisk/home/user/miniconda3/envs/ntng_bert
'''
I found a workaround [here](https://stackoverflow.com/questions/60580332/poetry-virtual-environment-already-activated) which is to run the command `source $(poetry env info --path)/bin/activate` however the following error raises
'''
source: no such file or directory: /localdisk/home/user/miniconda3/envs/ntng_bert/bin/activate
'''

Any idea why this error happens? 
Thanks

**Comment by oscarkey** [comment]
hey!

I think this is actually okay. If you run `poetry install` inside a conda environment then Poetry will install into the conda environment rather than creating its own. Thus when you run `poetry shell` while the conda environment is activated you get the `Virtual environment already activated` message, but it's not an error. If you just run your Python command, does it work?

**Comment by shiwenqin** [comment]
Thanks for the reply, but sadly no, error message is the following:
'''
Error executing job with overrides: ['name=trailrun', 'budget=1', 'seed=32']
Traceback (most recent call last):
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/pretrain_bert.py", line 240, in launch
    cramming.utils.main_launcher(cfg, main_training_process, job_name="pretraining")
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/utils.py", line 62, in main_launcher
    main_fn(cfg, setup)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/pretrain_bert.py", line 24, in main_training_process
    model = cramming.construct_model(cfg.arch, cfg.data.vocab_size)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/construction.py", line 22, in construct_model
    model = construct_scriptable_bert(cfg_arch, vocab_size, downstream_classes)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/scriptable_bert.py", line 33, in construct_scriptable_bert
    model = ScriptableLMForPreTraining(config)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/scriptable_bert.py", line 142, in __init__
    self.encoder = ScriptableLM(config)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/scriptable_bert.py", line 69, in __init__
    self.layers = torch.nn.ModuleList([layer_fn(idx, self.cfg) for idx in range(self.cfg.num_transformer_layers)])
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/scriptable_bert.py", line 69, in <listcomp>
    self.layers = torch.nn.ModuleList([layer_fn(idx, self.cfg) for idx in range(self.cfg.num_transformer_layers)])
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/components.py", line 94, in __init__
    self.attn = AttentionComponent(
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/components.py", line 51, in __init__
    self.self_attention = get_attention_mechanism(idx, hidden_size, cfg_attention)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/attention.py", line 25, in get_attention_mechanism
    mechanism = FlashMultiHeadAttention(hidden_size, cfg_attention)
  File "/localdisk/home/user/Work/Repositories/NoTrainNoGain/bert/cramming/architectures/attention.py", line 277, in __init__
    from flash_attn.flash_attention import FlashMHA
  File "/localdisk/home/user/miniconda3/envs/ntng_bert/lib/python3.10/site-packages/flash_attn/flash_attention.py", line 7, in <module>
    from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func
  File "/localdisk/home/user/miniconda3/envs/ntng_bert/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 5, in <module>
    import flash_attn_cuda
ImportError: /localdisk/home/user/miniconda3/envs/ntng_bert/lib/python3.10/site-packages/flash_attn_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
'''

**Comment by oscarkey** [comment]
It looks like flash attention didn't install correctly.

Are you just trying to reproduce our results, or are you planning to develop something further based on this code? If it's the latter, I would suggest updating the code to work with PyTorch 2.1 . This has flash attention built in (see [here](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html)), which will avoid these installation issues and be better in the long run.

**Comment by shiwenqin** [comment]
Sorry for the slow response, I think update to Pytorch 2 will indeed be a better option.

Thanks!
